backend:
  name: "git-gateway"
  branch: "master"

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Display Images", name: "images", widget: "list", fields: [{label: "Image", name: "path", widget: "image"}, {label: "Text", name: "text", widget: "string"}]}
          - {label: "About", name: "about", widget: "object", fields: [{label: "Image", name: "image", widget: "image"}, {label: "Heading", name: "heading", widget: "string"}, {label: "Alt", name: "alt", widget: "string"}, {label: "Description", name: "description", widget: "text"}]}
          - {label: "Cards", name: "cards", widget: "list", fields: [{label: "Image", name: "image", widget: "image"}, {label: "Label", name: "label", widget: "string"}, {label: "Link", name: "link", widget: "string"}]}
      - file: "src/pages/cakes.md"
        label: "Cakes Page"
        name: "cakes"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "cakes-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Display Image", name: "jumbotron", widget: "image"}
          - {label: "Categories", name: "categories", widget: "list", fields: [{label: "Name", name: "name", widget: "string"}, {label: "About", name: "about", widget: "object", fields: [{label: "Image", name: "image", widget: "image"}, {label: "Heading", name: "heading", widget: "string"}, {label: "Alt", name: "alt", widget: "string"}, {label: "Description", name: "description", widget: "text"}]}, {label: "Cards", name: "cards", widget: "list", fields: [{label: "Image", name: "image", widget: "image"}, {label: "Alt", name: "alt", widget: "string"}, {label: "Label", name: "label", widget: "string"}]}]}
      - file: "src/pages/pastries.md"
        label: "Pastries Page"
        name: "pastries"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "pastries-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Display Image", name: "jumbotron", widget: "image"}
          - {label: "Pastries", name: "pastries", widget: "list", fields: [{label: "Image", name: "image", widget: "image"}, {label: "Alt", name: "alt", widget: "string"}, {label: "Label", name: "label", widget: "string"}]}